version: "2"
volumes:
    wallet_build: {}

services:
    web-wallet-prod:
        build:
            context: .
            args:
                - PLAYCHAIN=prod
        image: playchain-web-explorer-prod
        mem_limit: 1g
        ports:
            - "18081:80"
    web-wallet-stage:
        build:
            context: .
            args:
                - PLAYCHAIN=stage
        image: playchain-web-explorer-stage
        mem_limit: 1g
        ports:
            - "18082:80"

