version: "2"
volumes:
    wallet_build: {}

services:
    web-wallet-prod:
        build:
            context: .
            args:
                - PLAYCHAIN=prod
        image: playchain-web-wallet-prod
        ports:
            - "8081:80"
        mem_limit: 2g
    web-wallet-stage:
        build:
            context: .
            args:
                - PLAYCHAIN=stage
        image: playchain-web-wallet-stage
        ports:
            - "8082:80"
        mem_limit: 2g
