version: "2"
volumes:
    wallet_build: {}

services:
    web-wallet-prod:
        build: .
        image: playchain-web-wallet-prod
        environment:
            - PLAYCHAIN=prod
        ports:
            - "8081:80"
        mem_limit: 1g

# web-wallet-stage:
#     build: .
#     image: playchain-web-wallet-stage
#     environment:
#         - PLAYCHAIN=stage
#     ports:
#         - "8082:80"
#     mem_limit: 1g
