version: "2"
volumes:
    wallet_build: {}

services:
    web-wallet-prod:
        build:
            context: .
            args:
                - LIVE_TESTNET=OFF  
        image: playchain-web-wallet-prod
        ports:
            - "8081:80"
        mem_limit: 1g
    web-wallet-stage:
        build:
            context: .
            args:
                - LIVE_TESTNET=ON
        image: playchain-web-wallet-stage
        ports:
            - "8082:80"
        mem_limit: 1g
